variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
    - build
    - test
    - deploy

default:
  image: "python:latest"

  cache:
    paths:
      - .cache/pip/
      - venv/
  before_script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt

migrations:
  stage: build
  tags:
      - docker
  script:
    - cd VSPOMs
    - python3 manage.py makemigrations
    # - python3 manage.py makemigrations myapp
    - python3 manage.py migrate
    - python3 manage.py check


django-tests:
  stage: test
  tags:
      - docker
  script:
    - python3 manage.py test

deploy:
  stage: deploy
  tags:
      - docker
  script: echo "Define your deployment script!"
  environment: production
